// flow-typed signature: ca18782009e4bdd52bdc4984f5c9309c
// flow-typed version: <<STUB>>/@types/react-native_v^0.60.5/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-native' {
  declare module.exports: any;
}
