// flow-typed signature: e54f62a801539a9d5538579661010f81
// flow-typed version: <<STUB>>/@types/react-native_v^0.57.63/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-native' {
  declare module.exports: any;
}
