// flow-typed signature: ab3c51144cd2d4d99c6300ded8c4c328
// flow-typed version: <<STUB>>/add_v^2.0.6/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'add'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'add' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'add/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'add/index' {
  declare module.exports: $Exports<'add'>;
}
declare module 'add/index.js' {
  declare module.exports: $Exports<'add'>;
}
declare module 'add/test.js' {
  declare module.exports: $Exports<'add/test'>;
}
