// flow-typed signature: 89b185ef3905698d5c4f0eff488f26fa
// flow-typed version: <<STUB>>/eslint-config-react-native_v^4.0.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-react-native' {
  declare module.exports: any;
}
