// flow-typed signature: 09e1c5ad52968151296279cf2e37eb47
// flow-typed version: <<STUB>>/jest-expo_v^33.0.2/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-expo/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-expo/jest-preset' {
  declare module.exports: any;
}

declare module 'jest-expo/src/index' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/assetFileTransformer' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/createMockConstants' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/expoModules' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/internalExpoModules' {
  declare module.exports: any;
}

declare module 'jest-expo/src/preset/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-expo/bin/jest.js' {
  declare module.exports: $Exports<'jest-expo/bin/jest'>;
}
declare module 'jest-expo/jest-preset.js' {
  declare module.exports: $Exports<'jest-expo/jest-preset'>;
}
declare module 'jest-expo/src/index.js' {
  declare module.exports: $Exports<'jest-expo/src/index'>;
}
declare module 'jest-expo/src/preset/assetFileTransformer.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/assetFileTransformer'>;
}
declare module 'jest-expo/src/preset/createMockConstants.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/createMockConstants'>;
}
declare module 'jest-expo/src/preset/expoModules.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/expoModules'>;
}
declare module 'jest-expo/src/preset/internalExpoModules.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/internalExpoModules'>;
}
declare module 'jest-expo/src/preset/setup.js' {
  declare module.exports: $Exports<'jest-expo/src/preset/setup'>;
}
