// flow-typed signature: 40ab96825fd6ba4e7e1092564e1ac7dc
// flow-typed version: <<STUB>>/jetifier_v^1.5.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jetifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jetifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jetifier/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jetifier/index' {
  declare module.exports: $Exports<'jetifier'>;
}
declare module 'jetifier/index.js' {
  declare module.exports: $Exports<'jetifier'>;
}
declare module 'jetifier/src/utils.js' {
  declare module.exports: $Exports<'jetifier/src/utils'>;
}
