// flow-typed signature: ea74b3a5e2efb0bc8cc3ccd7f3372778
// flow-typed version: <<STUB>>/jetifier_v^1.6.4/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jetifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jetifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jetifier/src/utils' {
  declare module.exports: any;
}

declare module 'jetifier/src/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jetifier/index' {
  declare module.exports: $Exports<'jetifier'>;
}
declare module 'jetifier/index.js' {
  declare module.exports: $Exports<'jetifier'>;
}
declare module 'jetifier/src/utils.js' {
  declare module.exports: $Exports<'jetifier/src/utils'>;
}
declare module 'jetifier/src/worker.js' {
  declare module.exports: $Exports<'jetifier/src/worker'>;
}
