// flow-typed signature: 004084dc50dfa933d88e32dd7c4a0563
// flow-typed version: <<STUB>>/node-authorization_v^2.0.2/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-authorization'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-authorization' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-authorization/lib/authorization' {
  declare module.exports: any;
}

declare module 'node-authorization/lib/profileCompiler' {
  declare module.exports: any;
}

declare module 'node-authorization/lib/selectOption' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-authorization/index' {
  declare module.exports: $Exports<'node-authorization'>;
}
declare module 'node-authorization/index.js' {
  declare module.exports: $Exports<'node-authorization'>;
}
declare module 'node-authorization/lib/authorization.js' {
  declare module.exports: $Exports<'node-authorization/lib/authorization'>;
}
declare module 'node-authorization/lib/profileCompiler.js' {
  declare module.exports: $Exports<'node-authorization/lib/profileCompiler'>;
}
declare module 'node-authorization/lib/selectOption.js' {
  declare module.exports: $Exports<'node-authorization/lib/selectOption'>;
}
