// flow-typed signature: 340f88150725d2f2965bdf02257a69dd
// flow-typed version: <<STUB>>/react-native-open-maps_v^0.3.3/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-open-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-open-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-open-maps/index' {
  declare module.exports: $Exports<'react-native-open-maps'>;
}
declare module 'react-native-open-maps/index.js' {
  declare module.exports: $Exports<'react-native-open-maps'>;
}
