// flow-typed signature: 72abf44744fa06faab0736d00a4ccecf
// flow-typed version: <<STUB>>/react-native-modalbox_v^1.7.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modalbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modalbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-modalbox/index' {
  declare module.exports: $Exports<'react-native-modalbox'>;
}
declare module 'react-native-modalbox/index.js' {
  declare module.exports: $Exports<'react-native-modalbox'>;
}
