// flow-typed signature: 37027b15d3d826a2624e42545a8f479a
// flow-typed version: <<STUB>>/react-native-charts-wrapper_v^0.5.5/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-charts-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-charts-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-charts-wrapper/lib/AxisIface' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/BarChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/BarLineChartBase' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/BubbleChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/CandleStickChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ChartBase' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ChartDataConfig' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ChartDataSetConfig' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/CombinedChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/HighlightEnhancer' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/HorizontalBarChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/LineChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/MoveEnhancer' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/PieChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/PieRadarChartBase' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/RadarChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ScaleEnhancer' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ScatterChart' {
  declare module.exports: any;
}

declare module 'react-native-charts-wrapper/lib/ScrollEnhancer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-charts-wrapper/index' {
  declare module.exports: $Exports<'react-native-charts-wrapper'>;
}
declare module 'react-native-charts-wrapper/index.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper'>;
}
declare module 'react-native-charts-wrapper/lib/AxisIface.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/AxisIface'>;
}
declare module 'react-native-charts-wrapper/lib/BarChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/BarChart'>;
}
declare module 'react-native-charts-wrapper/lib/BarLineChartBase.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/BarLineChartBase'>;
}
declare module 'react-native-charts-wrapper/lib/BubbleChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/BubbleChart'>;
}
declare module 'react-native-charts-wrapper/lib/CandleStickChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/CandleStickChart'>;
}
declare module 'react-native-charts-wrapper/lib/ChartBase.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ChartBase'>;
}
declare module 'react-native-charts-wrapper/lib/ChartDataConfig.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ChartDataConfig'>;
}
declare module 'react-native-charts-wrapper/lib/ChartDataSetConfig.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ChartDataSetConfig'>;
}
declare module 'react-native-charts-wrapper/lib/CombinedChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/CombinedChart'>;
}
declare module 'react-native-charts-wrapper/lib/HighlightEnhancer.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/HighlightEnhancer'>;
}
declare module 'react-native-charts-wrapper/lib/HorizontalBarChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/HorizontalBarChart'>;
}
declare module 'react-native-charts-wrapper/lib/LineChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/LineChart'>;
}
declare module 'react-native-charts-wrapper/lib/MoveEnhancer.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/MoveEnhancer'>;
}
declare module 'react-native-charts-wrapper/lib/PieChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/PieChart'>;
}
declare module 'react-native-charts-wrapper/lib/PieRadarChartBase.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/PieRadarChartBase'>;
}
declare module 'react-native-charts-wrapper/lib/RadarChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/RadarChart'>;
}
declare module 'react-native-charts-wrapper/lib/ScaleEnhancer.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ScaleEnhancer'>;
}
declare module 'react-native-charts-wrapper/lib/ScatterChart.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ScatterChart'>;
}
declare module 'react-native-charts-wrapper/lib/ScrollEnhancer.js' {
  declare module.exports: $Exports<'react-native-charts-wrapper/lib/ScrollEnhancer'>;
}
