// flow-typed signature: 08a026a934d420c7e135cbf3a97e825c
// flow-typed version: <<STUB>>/react-native-clean-project_v^3.2.4/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-clean-project'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-clean-project' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-clean-project/jest.config' {
  declare module.exports: any;
}

declare module 'react-native-clean-project/react-native.config' {
  declare module.exports: any;
}

declare module 'react-native-clean-project/source' {
  declare module.exports: any;
}

declare module 'react-native-clean-project/source/internals/executor' {
  declare module.exports: any;
}

declare module 'react-native-clean-project/source/internals/options' {
  declare module.exports: any;
}

declare module 'react-native-clean-project/source/internals/tasks' {
  declare module.exports: any;
}

declare module 'react-native-clean-project/source/plugin' {
  declare module.exports: any;
}

declare module 'react-native-clean-project/test/tasks.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-clean-project/jest.config.js' {
  declare module.exports: $Exports<'react-native-clean-project/jest.config'>;
}
declare module 'react-native-clean-project/react-native.config.js' {
  declare module.exports: $Exports<'react-native-clean-project/react-native.config'>;
}
declare module 'react-native-clean-project/source/index' {
  declare module.exports: $Exports<'react-native-clean-project/source'>;
}
declare module 'react-native-clean-project/source/index.js' {
  declare module.exports: $Exports<'react-native-clean-project/source'>;
}
declare module 'react-native-clean-project/source/internals/executor.js' {
  declare module.exports: $Exports<'react-native-clean-project/source/internals/executor'>;
}
declare module 'react-native-clean-project/source/internals/options.js' {
  declare module.exports: $Exports<'react-native-clean-project/source/internals/options'>;
}
declare module 'react-native-clean-project/source/internals/tasks.js' {
  declare module.exports: $Exports<'react-native-clean-project/source/internals/tasks'>;
}
declare module 'react-native-clean-project/source/plugin.js' {
  declare module.exports: $Exports<'react-native-clean-project/source/plugin'>;
}
declare module 'react-native-clean-project/test/tasks.test.js' {
  declare module.exports: $Exports<'react-native-clean-project/test/tasks.test'>;
}
