// flow-typed signature: 15892483c96481bee9cb0f1ec45ce9b6
// flow-typed version: <<STUB>>/react-native-responsive-ui_v^2.1.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-responsive-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-responsive-ui' {
  declare module.exports: any;
}
