// flow-typed signature: 2058f4840f931dbff1e40756446defbf
// flow-typed version: <<STUB>>/react-native-htmlview_v^0.15.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-htmlview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-htmlview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-htmlview/AutoSizedImage' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/example/Example' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/htmlToElement' {
  declare module.exports: any;
}

declare module 'react-native-htmlview/HTMLView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-htmlview/AutoSizedImage.js' {
  declare module.exports: $Exports<'react-native-htmlview/AutoSizedImage'>;
}
declare module 'react-native-htmlview/babel.config.js' {
  declare module.exports: $Exports<'react-native-htmlview/babel.config'>;
}
declare module 'react-native-htmlview/example/Example.js' {
  declare module.exports: $Exports<'react-native-htmlview/example/Example'>;
}
declare module 'react-native-htmlview/htmlToElement.js' {
  declare module.exports: $Exports<'react-native-htmlview/htmlToElement'>;
}
declare module 'react-native-htmlview/HTMLView.js' {
  declare module.exports: $Exports<'react-native-htmlview/HTMLView'>;
}
declare module 'react-native-htmlview/index' {
  declare module.exports: $Exports<'react-native-htmlview'>;
}
declare module 'react-native-htmlview/index.js' {
  declare module.exports: $Exports<'react-native-htmlview'>;
}
