// flow-typed signature: 20ca6faca6f715dd71fb561d7c0413e4
// flow-typed version: <<STUB>>/react-native-responsive-ui_v^1.1.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-responsive-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-responsive-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-responsive-ui/App' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/App.test' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/components/BackgroundImage' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/components/Button' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/components/Container' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/components/Header' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/components/Images' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/components' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/components/Title' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/drawer/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/drawer' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/home/Home' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/home' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/login/Field' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/login' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/login/Login' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/example/login/Mark' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/flow/native-base' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/flow/react-native' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/flow/react-navigation' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/lib/Device' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/lib' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/lib/MediaQuery' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/lib/MediaQuerySelector' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/lib/Responsive' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/lib/ResponsiveComponent' {
  declare module.exports: any;
}

declare module 'react-native-responsive-ui/lib/ResponsiveStyleSheet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-responsive-ui/App.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/App'>;
}
declare module 'react-native-responsive-ui/App.test.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/App.test'>;
}
declare module 'react-native-responsive-ui/example/components/BackgroundImage.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/components/BackgroundImage'>;
}
declare module 'react-native-responsive-ui/example/components/Button.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/components/Button'>;
}
declare module 'react-native-responsive-ui/example/components/Container.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/components/Container'>;
}
declare module 'react-native-responsive-ui/example/components/Header.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/components/Header'>;
}
declare module 'react-native-responsive-ui/example/components/Images.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/components/Images'>;
}
declare module 'react-native-responsive-ui/example/components/index' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/components'>;
}
declare module 'react-native-responsive-ui/example/components/index.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/components'>;
}
declare module 'react-native-responsive-ui/example/components/Title.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/components/Title'>;
}
declare module 'react-native-responsive-ui/example/drawer/Drawer.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/drawer/Drawer'>;
}
declare module 'react-native-responsive-ui/example/drawer/index' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/drawer'>;
}
declare module 'react-native-responsive-ui/example/drawer/index.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/drawer'>;
}
declare module 'react-native-responsive-ui/example/home/Home.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/home/Home'>;
}
declare module 'react-native-responsive-ui/example/home/index' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/home'>;
}
declare module 'react-native-responsive-ui/example/home/index.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/home'>;
}
declare module 'react-native-responsive-ui/example/login/Field.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/login/Field'>;
}
declare module 'react-native-responsive-ui/example/login/index' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/login'>;
}
declare module 'react-native-responsive-ui/example/login/index.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/login'>;
}
declare module 'react-native-responsive-ui/example/login/Login.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/login/Login'>;
}
declare module 'react-native-responsive-ui/example/login/Mark.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/example/login/Mark'>;
}
declare module 'react-native-responsive-ui/flow/native-base.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/flow/native-base'>;
}
declare module 'react-native-responsive-ui/flow/react-native.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/flow/react-native'>;
}
declare module 'react-native-responsive-ui/flow/react-navigation.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/flow/react-navigation'>;
}
declare module 'react-native-responsive-ui/lib/Device.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/lib/Device'>;
}
declare module 'react-native-responsive-ui/lib/index' {
  declare module.exports: $Exports<'react-native-responsive-ui/lib'>;
}
declare module 'react-native-responsive-ui/lib/index.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/lib'>;
}
declare module 'react-native-responsive-ui/lib/MediaQuery.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/lib/MediaQuery'>;
}
declare module 'react-native-responsive-ui/lib/MediaQuerySelector.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/lib/MediaQuerySelector'>;
}
declare module 'react-native-responsive-ui/lib/Responsive.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/lib/Responsive'>;
}
declare module 'react-native-responsive-ui/lib/ResponsiveComponent.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/lib/ResponsiveComponent'>;
}
declare module 'react-native-responsive-ui/lib/ResponsiveStyleSheet.js' {
  declare module.exports: $Exports<'react-native-responsive-ui/lib/ResponsiveStyleSheet'>;
}
