// flow-typed signature: 6a5e29bf85db799e714c8753bd03bca7
// flow-typed version: <<STUB>>/react-native-carousel-view_v^0.5.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-carousel-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-carousel-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-carousel-view/flow-typed/npm/react-native_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-native-carousel-view/src/carousel' {
  declare module.exports: any;
}

declare module 'react-native-carousel-view/src/carouselPager.android' {
  declare module.exports: any;
}

declare module 'react-native-carousel-view/src/carouselPager.ios' {
  declare module.exports: any;
}

declare module 'react-native-carousel-view/src/styles/carousel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-carousel-view/flow-typed/npm/react-native_vx.x.x.js' {
  declare module.exports: $Exports<'react-native-carousel-view/flow-typed/npm/react-native_vx.x.x'>;
}
declare module 'react-native-carousel-view/src/carousel.js' {
  declare module.exports: $Exports<'react-native-carousel-view/src/carousel'>;
}
declare module 'react-native-carousel-view/src/carouselPager.android.js' {
  declare module.exports: $Exports<'react-native-carousel-view/src/carouselPager.android'>;
}
declare module 'react-native-carousel-view/src/carouselPager.ios.js' {
  declare module.exports: $Exports<'react-native-carousel-view/src/carouselPager.ios'>;
}
declare module 'react-native-carousel-view/src/styles/carousel.js' {
  declare module.exports: $Exports<'react-native-carousel-view/src/styles/carousel'>;
}
