// flow-typed signature: a4519e71a519f01cfa913deb896b2959
// flow-typed version: <<STUB>>/react-native-google-maps-directions_v^2.1.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-google-maps-directions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-google-maps-directions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-google-maps-directions/index' {
  declare module.exports: $Exports<'react-native-google-maps-directions'>;
}
declare module 'react-native-google-maps-directions/index.js' {
  declare module.exports: $Exports<'react-native-google-maps-directions'>;
}
