// flow-typed signature: d6af51041f9dedbf21f5605e5a08b462
// flow-typed version: <<STUB>>/react-native-size-matters_v^0.2.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-size-matters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-size-matters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-size-matters/extend' {
  declare module.exports: any;
}

declare module 'react-native-size-matters/lib/deep-map' {
  declare module.exports: any;
}

declare module 'react-native-size-matters/lib/extend/scaling-utils.extend' {
  declare module.exports: any;
}

declare module 'react-native-size-matters/lib/ScaledSheet' {
  declare module.exports: any;
}

declare module 'react-native-size-matters/lib/scaling-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-size-matters/extend.js' {
  declare module.exports: $Exports<'react-native-size-matters/extend'>;
}
declare module 'react-native-size-matters/index' {
  declare module.exports: $Exports<'react-native-size-matters'>;
}
declare module 'react-native-size-matters/index.js' {
  declare module.exports: $Exports<'react-native-size-matters'>;
}
declare module 'react-native-size-matters/lib/deep-map.js' {
  declare module.exports: $Exports<'react-native-size-matters/lib/deep-map'>;
}
declare module 'react-native-size-matters/lib/extend/scaling-utils.extend.js' {
  declare module.exports: $Exports<'react-native-size-matters/lib/extend/scaling-utils.extend'>;
}
declare module 'react-native-size-matters/lib/ScaledSheet.js' {
  declare module.exports: $Exports<'react-native-size-matters/lib/ScaledSheet'>;
}
declare module 'react-native-size-matters/lib/scaling-utils.js' {
  declare module.exports: $Exports<'react-native-size-matters/lib/scaling-utils'>;
}
