// flow-typed signature: ef0732a46adab1f5ed99a635015ed075
// flow-typed version: <<STUB>>/react-native-sensitive-info_v^5.4.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-sensitive-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-sensitive-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-sensitive-info/RNSensitiveInfo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-sensitive-info/RNSensitiveInfo.js' {
  declare module.exports: $Exports<'react-native-sensitive-info/RNSensitiveInfo'>;
}
