// flow-typed signature: 71bfa71a262f36bd5221b1ca923a44d1
// flow-typed version: <<STUB>>/react-native-recaptcha-v3_v0.0.16/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-recaptcha-v3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-recaptcha-v3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-recaptcha-v3/MessageWebView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-recaptcha-v3/index' {
  declare module.exports: $Exports<'react-native-recaptcha-v3'>;
}
declare module 'react-native-recaptcha-v3/index.js' {
  declare module.exports: $Exports<'react-native-recaptcha-v3'>;
}
declare module 'react-native-recaptcha-v3/MessageWebView.js' {
  declare module.exports: $Exports<'react-native-recaptcha-v3/MessageWebView'>;
}
