// flow-typed signature: 1a683bbf67e28578598299e7980e5a9e
// flow-typed version: <<STUB>>/rn-secure-storage_v^1.1.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rn-secure-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rn-secure-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rn-secure-storage/index' {
  declare module.exports: $Exports<'rn-secure-storage'>;
}
declare module 'rn-secure-storage/index.js' {
  declare module.exports: $Exports<'rn-secure-storage'>;
}
