// flow-typed signature: 0f141de2ca0cda3d373c4d4852c47520
// flow-typed version: <<STUB>>/schedule_v^0.5.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'schedule'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'schedule' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'schedule/cjs/schedule-tracing.development' {
  declare module.exports: any;
}

declare module 'schedule/cjs/schedule-tracing.production.min' {
  declare module.exports: any;
}

declare module 'schedule/cjs/schedule-tracing.profiling.min' {
  declare module.exports: any;
}

declare module 'schedule/cjs/schedule.development' {
  declare module.exports: any;
}

declare module 'schedule/cjs/schedule.production.min' {
  declare module.exports: any;
}

declare module 'schedule/tracing-profiling' {
  declare module.exports: any;
}

declare module 'schedule/tracing' {
  declare module.exports: any;
}

declare module 'schedule/umd/schedule-tracing.development' {
  declare module.exports: any;
}

declare module 'schedule/umd/schedule-tracing.production.min' {
  declare module.exports: any;
}

declare module 'schedule/umd/schedule-tracing.profiling.min' {
  declare module.exports: any;
}

declare module 'schedule/umd/schedule.development' {
  declare module.exports: any;
}

declare module 'schedule/umd/schedule.production.min' {
  declare module.exports: any;
}

declare module 'schedule/umd/schedule.profiling.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'schedule/cjs/schedule-tracing.development.js' {
  declare module.exports: $Exports<'schedule/cjs/schedule-tracing.development'>;
}
declare module 'schedule/cjs/schedule-tracing.production.min.js' {
  declare module.exports: $Exports<'schedule/cjs/schedule-tracing.production.min'>;
}
declare module 'schedule/cjs/schedule-tracing.profiling.min.js' {
  declare module.exports: $Exports<'schedule/cjs/schedule-tracing.profiling.min'>;
}
declare module 'schedule/cjs/schedule.development.js' {
  declare module.exports: $Exports<'schedule/cjs/schedule.development'>;
}
declare module 'schedule/cjs/schedule.production.min.js' {
  declare module.exports: $Exports<'schedule/cjs/schedule.production.min'>;
}
declare module 'schedule/index' {
  declare module.exports: $Exports<'schedule'>;
}
declare module 'schedule/index.js' {
  declare module.exports: $Exports<'schedule'>;
}
declare module 'schedule/tracing-profiling.js' {
  declare module.exports: $Exports<'schedule/tracing-profiling'>;
}
declare module 'schedule/tracing.js' {
  declare module.exports: $Exports<'schedule/tracing'>;
}
declare module 'schedule/umd/schedule-tracing.development.js' {
  declare module.exports: $Exports<'schedule/umd/schedule-tracing.development'>;
}
declare module 'schedule/umd/schedule-tracing.production.min.js' {
  declare module.exports: $Exports<'schedule/umd/schedule-tracing.production.min'>;
}
declare module 'schedule/umd/schedule-tracing.profiling.min.js' {
  declare module.exports: $Exports<'schedule/umd/schedule-tracing.profiling.min'>;
}
declare module 'schedule/umd/schedule.development.js' {
  declare module.exports: $Exports<'schedule/umd/schedule.development'>;
}
declare module 'schedule/umd/schedule.production.min.js' {
  declare module.exports: $Exports<'schedule/umd/schedule.production.min'>;
}
declare module 'schedule/umd/schedule.profiling.min.js' {
  declare module.exports: $Exports<'schedule/umd/schedule.profiling.min'>;
}
