// flow-typed signature: 2fea2352c27f49f8616e147cb453046e
// flow-typed version: <<STUB>>/@react-native-community/push-notification-ios_v^1.0.2/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/push-notification-ios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/push-notification-ios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/push-notification-ios/js' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/push-notification-ios/js/index' {
  declare module.exports: $Exports<'@react-native-community/push-notification-ios/js'>;
}
declare module '@react-native-community/push-notification-ios/js/index.js' {
  declare module.exports: $Exports<'@react-native-community/push-notification-ios/js'>;
}
