import palette from './palette';

// Light theme
export default {
  infoLight: palette.infoLight,
  primaryLight: palette.primaryLight,
  dangerLight: palette.dangerLight,
  disabledLight: palette.disabledLight,
  disabledDark: palette.disabledDark,
  success: palette.success,
  warning: palette.warning,
  warningLight: palette.warningLight,
  warningDark: palette.warningDark,
  danger: palette.danger,
  info: palette.info,
  light: palette.light,
  primary: palette.primary,
  primaryDark: palette.primaryDark,
  darkLight: palette.darkLight,
  disabled: palette.disabled,
  backgroundHeader: palette.light,
  modalBackgroundColor: palette.light,
  listBackgroundHeader: palette.disabled,
  listItemSelected: '#BFBFBF',
  background: '#f2f2f2',
  borderColor: palette.dark,
  textColor: '#272727',
  placeholderTextColor: palette.disabledDark,
  inverseTextColor: palette.light,
  subTextColor: palette.disabledDark,
  buttonBg: palette.disabled,
  touchableBackgroundColor: 'rgba(0,0,0,0.4)',
  selectFieldBackgroundColor: '#eeeeee',
  selectDropdownBackgroundColor: '#eeeeee',
  listHeaderBackground: palette.light,
  listItemBackground: palette.light,
  mapClusterBorder: '#272727',
  lightDark: null
};
